[0.4.16][MSVCRT][CRT][UCRT] Disable intrinsic string functions on MSVC
[MSVCRT][CRT][UCRT] Disable intrinsic string functions on MSVC (#9157)
Commit hash: 300e1d525dbba65ab05e8a0b895baa007202c9fe

VS2022 version 17.2 and later (`_MSC_VER >= 1932`) added new intrinsic
functions (`strncmp`, `strncpy`, `wcsncmp`, and `wcsncpy`).
As we implement these ourselves, we have to avoid compiler error C2169.

This problem surfaced with a recent GitHub Actions update:
https://github.com/actions/runner-images/issues/14017

Use `#pragma function(...)` to disable new intrinsic functions.

[CRT][UCRT][MSVCRT] intrinsic functions: Follow-up of #9157 (#9226)
Commit hash: 0572d360240fde257dc54925c43bd3b549bc2080

JIRA issue: CORE-20617
@learn-more found #9157 breaks the build as follows:
> error C2220: the following warning is treated as an error
> warning C4163: 'strncmp': not available as an intrinsic function
> warning C4163: 'strncpy': not available as an intrinsic function
_MSC_VER=1932 was not the version that the intrinsic functions
(strncmp, strncpy, wcsncmp, wcsncpy) added.
Using Compiler Explorer could detect the correct version:
_MSC_VER=1950.